# Using the calibration algorithm
bias: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
gripper_com_frame_id: end_effector
gripper_com_pose: [-0.008, 0.089, 0.0, 0.0, 0.0, 0.0]
gripper_mass: 2.52
#~ Inertia:       [Ixx,     Ixy,    Ixz,      Iyy,      Iyz,    Izz]
gripper_inertia:  [7300e-6, 0,      -650e-6,  8800e-6,  0,      7000e-6]


