joint_state_controller:
  type: joint_state_controller/JointStateController
  # Hz
  publish_rate: 1000
# left arm
left_SA:
  type: effort_controllers/JointPositionController
  joint: left_SA
  pid: {p: 10000, i: 0, d: 100}
left_SE:
  type: effort_controllers/JointPositionController
  joint: left_SE
  pid: {p: 1000000, i: 0, d: 100}
left_WP:
  type: effort_controllers/JointPositionController
  joint: left_WP
  pid: {p: 10000, i: 0, d: 100}
left_WY:
  type: effort_controllers/JointPositionController
  joint: left_WY
  pid: {p: 3000, i: 0, d: 50}
left_WR:
  type: effort_controllers/JointPositionController
  joint: left_WR
  pid: {p: 100, i: 0, d: 0}
left_linkage_tr:
  type: effort_controllers/JointPositionController
  joint: left_linkage_tr
  pid: {p: 10000, i: 0, d: 100}
left_linkage_tl:
  type: effort_controllers/JointPositionController
  joint: left_linkage_tl
  pid: {p: 1000, i: 0, d: 10}
left_linkage_bl:
  type: effort_controllers/JointPositionController
  joint: left_linkage_bl
  pid: {p: 100, i: 0, d: 1}

# right arm
right_SA:
  type: effort_controllers/JointPositionController
  joint: right_SA
  pid: {p: 10000, i: 0, d: 100}
right_SE:
  type: effort_controllers/JointPositionController
  joint: right_SE
  pid: {p: 1000000, i: 0, d: 100}
right_WP:
  type: effort_controllers/JointPositionController
  joint: right_WP
  pid: {p: 10000, i: 0, d: 100}
right_WY:
  type: effort_controllers/JointPositionController
  joint: right_WY
  pid: {p: 3000, i: 0, d: 50}
right_WR:
  type: effort_controllers/JointPositionController
  joint: right_WR
  pid: {p: 100, i: 0, d: 0}
right_linkage_tr:
  type: effort_controllers/JointPositionController
  joint: right_linkage_tr
  pid: {p: 10000, i: 0, d: 100}
right_linkage_tl:
  type: effort_controllers/JointPositionController
  joint: right_linkage_tl
  pid: {p: 1000, i: 0, d: 10}
right_linkage_bl:
  type: effort_controllers/JointPositionController
  joint: right_linkage_bl
  pid: {p: 100, i: 0, d: 1}
